# Generated by Django 2.2.5 on 2019-12-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191104_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseimage',
            field=models.ImageField(default='SOME STRING', upload_to='courseimg'),
        ),
    ]
